function dataOut = preprocessForICA (dataIn)

%% PREPROCESSFORICA filters and remove mean
% TO-DO: Add method information
% 
% See also filterChebyShev.m
%
% Carlos Aguilar - April 1st 2k15
%
% dataIn is a struct
% dataIn.signalNames
% dataIn.signalData
% dataIn.fs

useFIR = true;

[~, lengthSignal]  = size(dataIn.signalData);



if useFIR
    
    dataSignalProc = filterFIR(dataIn.signalData, dataIn.fs, ...
            'filterOrder' , 256, ...
            'filterType'      ,'high', ...
            'filterFrequency' , 1.5, ...
            'showFilterDesign', false);

    dataSignalProc = filterFIR(dataSignalProc, dataIn.fs, ...
            'filterOrder' , 256, ...
            'filterType'      ,'low', ...
            'filterFrequency' , 30, ...        
            'showFilterDesign', false);    
    
else
    
    dataSignalProcs = filterChebyShev(dataIn.signalData, dataIn.fs, ...
            'filterOrder' , 6, 'filterRipple', 30, ...
            'filterFrequency' , 1.0, ...
            'filterType'      ,'high', ...
            'showFilterDesign', false);     

    dataSignalProc = filterChebyShev(dataSignalProcs, dataIn.fs, ...
            'filterOrder' , 6, 'filterRipple', 30, ...
            'filterFrequency' , 40.0 , ...
            'filterType'      ,'low', ...
            'showFilterDesign', false); 
    
end
    
% remove the mean
dataSignalProcWhite = ...
  dataSignalProc - mean(dataSignalProc,2)*ones(1,lengthSignal);

dataOut.signalData  = dataSignalProcWhite;