figureLeft,
plot3(x,y,z, '*')

meshCentroid = mean(currentVert, 1);

hold on,

patch('Faces'          , facets, ...
      'Vertices'       , 0.5+currentVert , ...
      'FaceVertexCData', [0 1 0], ...
      'FaceColor'      , 'flat'      , ...
      'facealpha'      , 0.4         , ...      
      'CDataMapping'   , 'direct');
    
    
hold on, 
trisurf(facets, x,y,5+z, ...
        'facealpha' , 0.35 )    