function [parallelPath, meridianPath, pathInfo] = ...
  getMeridianAndParallel(selectedPointIdx, pointsPosition)

% center the dataset
pointsCentroid = mean(pointsPosition, 1);
pointsCentered = bsxfun(@minus, pointsPosition, pointsCentroid);

% Move along the azimuth. Go to spherical coordinates to sort the points by
% azimuth, so we can move the camera along the horizontal axis.
[currentAzimuth, currentElevation, currentRadius] = ...
  cart2sph(pointsCentered(:,1), ...
  pointsCentered(:,2), ...
  pointsCentered(:,3));

%  Plot a new figure
[parallelPath, meridianPath, pathInfo] = ...
  getMeridianAndParallelV4(currentAzimuth, currentElevation, ...
  currentRadius, selectedPointIdx, pointsCentered);